/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/alauda/kube-ovn/pkg/apis/kubeovn/v1"
	scheme "github.com/alauda/kube-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LogicalPortPairsGetter has a method to return a LogicalPortPairInterface.
// A group's client should implement this interface.
type LogicalPortPairsGetter interface {
	LogicalPortPairs(namespace string) LogicalPortPairInterface
}

// LogicalPortPairInterface has methods to work with LogicalPortPair resources.
type LogicalPortPairInterface interface {
	Create(*v1.LogicalPortPair) (*v1.LogicalPortPair, error)
	Update(*v1.LogicalPortPair) (*v1.LogicalPortPair, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.LogicalPortPair, error)
	List(opts metav1.ListOptions) (*v1.LogicalPortPairList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.LogicalPortPair, err error)
	LogicalPortPairExpansion
}

// logicalPortPairs implements LogicalPortPairInterface
type logicalPortPairs struct {
	client rest.Interface
	ns     string
}

// newLogicalPortPairs returns a LogicalPortPairs
func newLogicalPortPairs(c *KubeovnV1Client, namespace string) *logicalPortPairs {
	return &logicalPortPairs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the logicalPortPair, and returns the corresponding logicalPortPair object, and an error if there is any.
func (c *logicalPortPairs) Get(name string, options metav1.GetOptions) (result *v1.LogicalPortPair, err error) {
	result = &v1.LogicalPortPair{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("logicalportpairs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LogicalPortPairs that match those selectors.
func (c *logicalPortPairs) List(opts metav1.ListOptions) (result *v1.LogicalPortPairList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.LogicalPortPairList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("logicalportpairs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested logicalPortPairs.
func (c *logicalPortPairs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("logicalportpairs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a logicalPortPair and creates it.  Returns the server's representation of the logicalPortPair, and an error, if there is any.
func (c *logicalPortPairs) Create(logicalPortPair *v1.LogicalPortPair) (result *v1.LogicalPortPair, err error) {
	result = &v1.LogicalPortPair{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("logicalportpairs").
		Body(logicalPortPair).
		Do().
		Into(result)
	return
}

// Update takes the representation of a logicalPortPair and updates it. Returns the server's representation of the logicalPortPair, and an error, if there is any.
func (c *logicalPortPairs) Update(logicalPortPair *v1.LogicalPortPair) (result *v1.LogicalPortPair, err error) {
	result = &v1.LogicalPortPair{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("logicalportpairs").
		Name(logicalPortPair.Name).
		Body(logicalPortPair).
		Do().
		Into(result)
	return
}

// Delete takes name of the logicalPortPair and deletes it. Returns an error if one occurs.
func (c *logicalPortPairs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("logicalportpairs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *logicalPortPairs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("logicalportpairs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched logicalPortPair.
func (c *logicalPortPairs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.LogicalPortPair, err error) {
	result = &v1.LogicalPortPair{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("logicalportpairs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
